name             "skeleton"
maintainer       "Alex Knoll"
maintainer_email "arknoll@gmail.com"
license          "Apache 2.0"
description      "Installs/configures nfs"
version          "0.1.0"
recipe           "drupal-nfs::default", "Installs/configures nfs"
